package com.yunhe.common.mapper;

import com.yunhe.common.model.domain.Orders;
import com.yunhe.common.model.domain.OrdersExample.Criteria;
import com.yunhe.common.model.domain.OrdersExample.Criterion;
import com.yunhe.common.model.domain.OrdersExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OrdersSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String countByExample(OrdersExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("orders");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String deleteByExample(OrdersExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("orders");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String insertSelective(Orders record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("orders");
        
        if (record.getOrderId() != null) {
            sql.VALUES("ORDER_ID", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.VALUES("USERNAME", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getScenicSpotName() != null) {
            sql.VALUES("SCENIC_SPOT_NAME", "#{scenicSpotName,jdbcType=VARCHAR}");
        }
        
        if (record.getAdultTicketsAccont() != null) {
            sql.VALUES("ADULT_TICKETS_ACCONT", "#{adultTicketsAccont,jdbcType=INTEGER}");
        }
        
        if (record.getChildTicketsAccount() != null) {
            sql.VALUES("CHILD_TICKETS_ACCOUNT", "#{childTicketsAccount,jdbcType=INTEGER}");
        }
        
        if (record.getOrderTotalPrice() != null) {
            sql.VALUES("ORDER_TOTAL_PRICE", "#{orderTotalPrice,jdbcType=DOUBLE}");
        }
        
        if (record.getOrderPaymentMethod() != null) {
            sql.VALUES("ORDER_PAYMENT_METHOD", "#{orderPaymentMethod,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOrderState() != null) {
            sql.VALUES("ORDER_STATE", "#{orderState,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String selectByExample(OrdersExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ORDER_ID");
        } else {
            sql.SELECT("ORDER_ID");
        }
        sql.SELECT("USERNAME");
        sql.SELECT("SCENIC_SPOT_NAME");
        sql.SELECT("ADULT_TICKETS_ACCONT");
        sql.SELECT("CHILD_TICKETS_ACCOUNT");
        sql.SELECT("ORDER_TOTAL_PRICE");
        sql.SELECT("ORDER_PAYMENT_METHOD");
        sql.SELECT("CREATE_TIME");
        sql.SELECT("ORDER_STATE");
        sql.FROM("orders");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Orders record = (Orders) parameter.get("record");
        OrdersExample example = (OrdersExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("orders");
        
        if (record.getOrderId() != null) {
            sql.SET("ORDER_ID = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.SET("USERNAME = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record.getScenicSpotName() != null) {
            sql.SET("SCENIC_SPOT_NAME = #{record.scenicSpotName,jdbcType=VARCHAR}");
        }
        
        if (record.getAdultTicketsAccont() != null) {
            sql.SET("ADULT_TICKETS_ACCONT = #{record.adultTicketsAccont,jdbcType=INTEGER}");
        }
        
        if (record.getChildTicketsAccount() != null) {
            sql.SET("CHILD_TICKETS_ACCOUNT = #{record.childTicketsAccount,jdbcType=INTEGER}");
        }
        
        if (record.getOrderTotalPrice() != null) {
            sql.SET("ORDER_TOTAL_PRICE = #{record.orderTotalPrice,jdbcType=DOUBLE}");
        }
        
        if (record.getOrderPaymentMethod() != null) {
            sql.SET("ORDER_PAYMENT_METHOD = #{record.orderPaymentMethod,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOrderState() != null) {
            sql.SET("ORDER_STATE = #{record.orderState,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("orders");
        
        sql.SET("ORDER_ID = #{record.orderId,jdbcType=VARCHAR}");
        sql.SET("USERNAME = #{record.username,jdbcType=VARCHAR}");
        sql.SET("SCENIC_SPOT_NAME = #{record.scenicSpotName,jdbcType=VARCHAR}");
        sql.SET("ADULT_TICKETS_ACCONT = #{record.adultTicketsAccont,jdbcType=INTEGER}");
        sql.SET("CHILD_TICKETS_ACCOUNT = #{record.childTicketsAccount,jdbcType=INTEGER}");
        sql.SET("ORDER_TOTAL_PRICE = #{record.orderTotalPrice,jdbcType=DOUBLE}");
        sql.SET("ORDER_PAYMENT_METHOD = #{record.orderPaymentMethod,jdbcType=VARCHAR}");
        sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("ORDER_STATE = #{record.orderState,jdbcType=INTEGER}");
        
        OrdersExample example = (OrdersExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String updateByPrimaryKeySelective(Orders record) {
        SQL sql = new SQL();
        sql.UPDATE("orders");
        
        if (record.getUsername() != null) {
            sql.SET("USERNAME = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getScenicSpotName() != null) {
            sql.SET("SCENIC_SPOT_NAME = #{scenicSpotName,jdbcType=VARCHAR}");
        }
        
        if (record.getAdultTicketsAccont() != null) {
            sql.SET("ADULT_TICKETS_ACCONT = #{adultTicketsAccont,jdbcType=INTEGER}");
        }
        
        if (record.getChildTicketsAccount() != null) {
            sql.SET("CHILD_TICKETS_ACCOUNT = #{childTicketsAccount,jdbcType=INTEGER}");
        }
        
        if (record.getOrderTotalPrice() != null) {
            sql.SET("ORDER_TOTAL_PRICE = #{orderTotalPrice,jdbcType=DOUBLE}");
        }
        
        if (record.getOrderPaymentMethod() != null) {
            sql.SET("ORDER_PAYMENT_METHOD = #{orderPaymentMethod,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOrderState() != null) {
            sql.SET("ORDER_STATE = #{orderState,jdbcType=INTEGER}");
        }
        
        sql.WHERE("ORDER_ID = #{orderId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    protected void applyWhere(SQL sql, OrdersExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}