package com.yunhe.common.mapper;

import com.yunhe.common.model.domain.Orders;
import com.yunhe.common.model.domain.OrdersExample;
import com.yunhe.common.model.domain.OrdersKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @SelectProvider(type=OrdersSqlProvider.class, method="countByExample")
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @DeleteProvider(type=OrdersSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Delete({
        "delete from orders",
        "where ORDER_ID = #{orderId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(OrdersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Insert({
        "insert into orders (ORDER_ID, USERNAME, ",
        "SCENIC_SPOT_NAME, ADULT_TICKETS_ACCONT, ",
        "CHILD_TICKETS_ACCOUNT, ORDER_TOTAL_PRICE, ",
        "ORDER_PAYMENT_METHOD, CREATE_TIME, ",
        "ORDER_STATE)",
        "values (#{orderId,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{scenicSpotName,jdbcType=VARCHAR}, #{adultTicketsAccont,jdbcType=INTEGER}, ",
        "#{childTicketsAccount,jdbcType=INTEGER}, #{orderTotalPrice,jdbcType=DOUBLE}, ",
        "#{orderPaymentMethod,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{orderState,jdbcType=INTEGER})"
    })
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @InsertProvider(type=OrdersSqlProvider.class, method="insertSelective")
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @SelectProvider(type=OrdersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USERNAME", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCENIC_SPOT_NAME", property="scenicSpotName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADULT_TICKETS_ACCONT", property="adultTicketsAccont", jdbcType=JdbcType.INTEGER),
        @Result(column="CHILD_TICKETS_ACCOUNT", property="childTicketsAccount", jdbcType=JdbcType.INTEGER),
        @Result(column="ORDER_TOTAL_PRICE", property="orderTotalPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="ORDER_PAYMENT_METHOD", property="orderPaymentMethod", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ORDER_STATE", property="orderState", jdbcType=JdbcType.INTEGER)
    })
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Select({
        "select",
        "ORDER_ID, USERNAME, SCENIC_SPOT_NAME, ADULT_TICKETS_ACCONT, CHILD_TICKETS_ACCOUNT, ",
        "ORDER_TOTAL_PRICE, ORDER_PAYMENT_METHOD, CREATE_TIME, ORDER_STATE",
        "from orders",
        "where ORDER_ID = #{orderId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USERNAME", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="SCENIC_SPOT_NAME", property="scenicSpotName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADULT_TICKETS_ACCONT", property="adultTicketsAccont", jdbcType=JdbcType.INTEGER),
        @Result(column="CHILD_TICKETS_ACCOUNT", property="childTicketsAccount", jdbcType=JdbcType.INTEGER),
        @Result(column="ORDER_TOTAL_PRICE", property="orderTotalPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="ORDER_PAYMENT_METHOD", property="orderPaymentMethod", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ORDER_STATE", property="orderState", jdbcType=JdbcType.INTEGER)
    })
    Orders selectByPrimaryKey(OrdersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Update({
        "update orders",
        "set USERNAME = #{username,jdbcType=VARCHAR},",
          "SCENIC_SPOT_NAME = #{scenicSpotName,jdbcType=VARCHAR},",
          "ADULT_TICKETS_ACCONT = #{adultTicketsAccont,jdbcType=INTEGER},",
          "CHILD_TICKETS_ACCOUNT = #{childTicketsAccount,jdbcType=INTEGER},",
          "ORDER_TOTAL_PRICE = #{orderTotalPrice,jdbcType=DOUBLE},",
          "ORDER_PAYMENT_METHOD = #{orderPaymentMethod,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "ORDER_STATE = #{orderState,jdbcType=INTEGER}",
        "where ORDER_ID = #{orderId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Orders record);
}