package com.yunhe.common.mapper;

import com.yunhe.common.model.domain.ScenicSpots;
import com.yunhe.common.model.domain.ScenicSpotsExample.Criteria;
import com.yunhe.common.model.domain.ScenicSpotsExample.Criterion;
import com.yunhe.common.model.domain.ScenicSpotsExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ScenicSpotsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String countByExample(ScenicSpotsExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("scenic_spots");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String deleteByExample(ScenicSpotsExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("scenic_spots");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String insertSelective(ScenicSpots record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("scenic_spots");
        
        if (record.getScenicSpotName() != null) {
            sql.VALUES("SCENIC_SPOT_NAME", "#{scenicSpotName,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentMethods() != null) {
            sql.VALUES("PAYMENT_METHODS", "#{paymentMethods,jdbcType=VARCHAR}");
        }
        
        if (record.getScenicSpotAddress() != null) {
            sql.VALUES("SCENIC_SPOT_ADDRESS", "#{scenicSpotAddress,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String selectByExample(ScenicSpotsExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("SCENIC_SPOT_NAME");
        } else {
            sql.SELECT("SCENIC_SPOT_NAME");
        }
        sql.SELECT("PAYMENT_METHODS");
        sql.SELECT("SCENIC_SPOT_ADDRESS");
        sql.FROM("scenic_spots");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ScenicSpots record = (ScenicSpots) parameter.get("record");
        ScenicSpotsExample example = (ScenicSpotsExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("scenic_spots");
        
        if (record.getScenicSpotName() != null) {
            sql.SET("SCENIC_SPOT_NAME = #{record.scenicSpotName,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentMethods() != null) {
            sql.SET("PAYMENT_METHODS = #{record.paymentMethods,jdbcType=VARCHAR}");
        }
        
        if (record.getScenicSpotAddress() != null) {
            sql.SET("SCENIC_SPOT_ADDRESS = #{record.scenicSpotAddress,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("scenic_spots");
        
        sql.SET("SCENIC_SPOT_NAME = #{record.scenicSpotName,jdbcType=VARCHAR}");
        sql.SET("PAYMENT_METHODS = #{record.paymentMethods,jdbcType=VARCHAR}");
        sql.SET("SCENIC_SPOT_ADDRESS = #{record.scenicSpotAddress,jdbcType=VARCHAR}");
        
        ScenicSpotsExample example = (ScenicSpotsExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String updateByPrimaryKeySelective(ScenicSpots record) {
        SQL sql = new SQL();
        sql.UPDATE("scenic_spots");
        
        if (record.getPaymentMethods() != null) {
            sql.SET("PAYMENT_METHODS = #{paymentMethods,jdbcType=VARCHAR}");
        }
        
        if (record.getScenicSpotAddress() != null) {
            sql.SET("SCENIC_SPOT_ADDRESS = #{scenicSpotAddress,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("SCENIC_SPOT_NAME = #{scenicSpotName,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spots
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    protected void applyWhere(SQL sql, ScenicSpotsExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}