package com.yunhe.common.mapper;

import com.yunhe.common.model.domain.Users;
import com.yunhe.common.model.domain.UsersExample;
import com.yunhe.common.model.domain.UsersKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @SelectProvider(type=UsersSqlProvider.class, method="countByExample")
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @DeleteProvider(type=UsersSqlProvider.class, method="deleteByExample")
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Delete({
        "delete from users",
        "where USERNAME = #{username,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(UsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Insert({
        "insert into users (USERNAME, PASSWORD, ",
        "USER_PHONE)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{userPhone,jdbcType=VARCHAR})"
    })
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @InsertProvider(type=UsersSqlProvider.class, method="insertSelective")
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @SelectProvider(type=UsersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="USERNAME", property="username", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PASSWORD", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_PHONE", property="userPhone", jdbcType=JdbcType.VARCHAR)
    })
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Select({
        "select",
        "USERNAME, PASSWORD, USER_PHONE",
        "from users",
        "where USERNAME = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="USERNAME", property="username", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PASSWORD", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_PHONE", property="userPhone", jdbcType=JdbcType.VARCHAR)
    })
    Users selectByPrimaryKey(UsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    @Update({
        "update users",
        "set PASSWORD = #{password,jdbcType=VARCHAR},",
          "USER_PHONE = #{userPhone,jdbcType=VARCHAR}",
        "where USERNAME = #{username,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Users record);
}