server:
  port: 8761

eureka:
  instance:
    hostname: eureka8761.com
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000