package com.yunhe.common.model.domain;

import java.util.Date;

public class Orders extends OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.USERNAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.SCENIC_SPOT_NAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String scenicSpotName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ADULT_TICKETS_ACCONT
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Integer adultTicketsAccont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.CHILD_TICKETS_ACCOUNT
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Integer childTicketsAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_TOTAL_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Double orderTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_PAYMENT_METHOD
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String orderPaymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.CREATE_TIME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_STATE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Integer orderState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.USERNAME
     *
     * @return the value of orders.USERNAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.USERNAME
     *
     * @param username the value for orders.USERNAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.SCENIC_SPOT_NAME
     *
     * @return the value of orders.SCENIC_SPOT_NAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getScenicSpotName() {
        return scenicSpotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.SCENIC_SPOT_NAME
     *
     * @param scenicSpotName the value for orders.SCENIC_SPOT_NAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setScenicSpotName(String scenicSpotName) {
        this.scenicSpotName = scenicSpotName == null ? null : scenicSpotName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ADULT_TICKETS_ACCONT
     *
     * @return the value of orders.ADULT_TICKETS_ACCONT
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Integer getAdultTicketsAccont() {
        return adultTicketsAccont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ADULT_TICKETS_ACCONT
     *
     * @param adultTicketsAccont the value for orders.ADULT_TICKETS_ACCONT
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setAdultTicketsAccont(Integer adultTicketsAccont) {
        this.adultTicketsAccont = adultTicketsAccont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.CHILD_TICKETS_ACCOUNT
     *
     * @return the value of orders.CHILD_TICKETS_ACCOUNT
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Integer getChildTicketsAccount() {
        return childTicketsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.CHILD_TICKETS_ACCOUNT
     *
     * @param childTicketsAccount the value for orders.CHILD_TICKETS_ACCOUNT
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setChildTicketsAccount(Integer childTicketsAccount) {
        this.childTicketsAccount = childTicketsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_TOTAL_PRICE
     *
     * @return the value of orders.ORDER_TOTAL_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Double getOrderTotalPrice() {
        return orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_TOTAL_PRICE
     *
     * @param orderTotalPrice the value for orders.ORDER_TOTAL_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setOrderTotalPrice(Double orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_PAYMENT_METHOD
     *
     * @return the value of orders.ORDER_PAYMENT_METHOD
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getOrderPaymentMethod() {
        return orderPaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_PAYMENT_METHOD
     *
     * @param orderPaymentMethod the value for orders.ORDER_PAYMENT_METHOD
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setOrderPaymentMethod(String orderPaymentMethod) {
        this.orderPaymentMethod = orderPaymentMethod == null ? null : orderPaymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.CREATE_TIME
     *
     * @return the value of orders.CREATE_TIME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.CREATE_TIME
     *
     * @param createTime the value for orders.CREATE_TIME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_STATE
     *
     * @return the value of orders.ORDER_STATE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_STATE
     *
     * @param orderState the value for orders.ORDER_STATE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }
}