package com.yunhe.common.model.domain;

public class OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_ID
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_ID
     *
     * @return the value of orders.ORDER_ID
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_ID
     *
     * @param orderId the value for orders.ORDER_ID
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}