package com.yunhe.common.model.domain;

public class ScenicSpots extends ScenicSpotsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spots.PAYMENT_METHODS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String paymentMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic_spots.SCENIC_SPOT_ADDRESS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String scenicSpotAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spots.PAYMENT_METHODS
     *
     * @return the value of scenic_spots.PAYMENT_METHODS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spots.PAYMENT_METHODS
     *
     * @param paymentMethods the value for scenic_spots.PAYMENT_METHODS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setPaymentMethods(String paymentMethods) {
        this.paymentMethods = paymentMethods == null ? null : paymentMethods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic_spots.SCENIC_SPOT_ADDRESS
     *
     * @return the value of scenic_spots.SCENIC_SPOT_ADDRESS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getScenicSpotAddress() {
        return scenicSpotAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic_spots.SCENIC_SPOT_ADDRESS
     *
     * @param scenicSpotAddress the value for scenic_spots.SCENIC_SPOT_ADDRESS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setScenicSpotAddress(String scenicSpotAddress) {
        this.scenicSpotAddress = scenicSpotAddress == null ? null : scenicSpotAddress.trim();
    }
}