package com.yunhe.common.model.domain;

public class Tickets extends TicketsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.ADULT_TICKET_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Double adultTicketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.CHILD_TICKET_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Double childTicketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.REMAINING_TICKETS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private Integer remainingTickets;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.ADULT_TICKET_PRICE
     *
     * @return the value of tickets.ADULT_TICKET_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Double getAdultTicketPrice() {
        return adultTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.ADULT_TICKET_PRICE
     *
     * @param adultTicketPrice the value for tickets.ADULT_TICKET_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setAdultTicketPrice(Double adultTicketPrice) {
        this.adultTicketPrice = adultTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.CHILD_TICKET_PRICE
     *
     * @return the value of tickets.CHILD_TICKET_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Double getChildTicketPrice() {
        return childTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.CHILD_TICKET_PRICE
     *
     * @param childTicketPrice the value for tickets.CHILD_TICKET_PRICE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setChildTicketPrice(Double childTicketPrice) {
        this.childTicketPrice = childTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.REMAINING_TICKETS
     *
     * @return the value of tickets.REMAINING_TICKETS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public Integer getRemainingTickets() {
        return remainingTickets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.REMAINING_TICKETS
     *
     * @param remainingTickets the value for tickets.REMAINING_TICKETS
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setRemainingTickets(Integer remainingTickets) {
        this.remainingTickets = remainingTickets;
    }
}