package com.yunhe.common.model.domain;

public class TicketsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.SCENIC_SPOT_NAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String scenicSpotName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.SCENIC_SPOT_NAME
     *
     * @return the value of tickets.SCENIC_SPOT_NAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getScenicSpotName() {
        return scenicSpotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.SCENIC_SPOT_NAME
     *
     * @param scenicSpotName the value for tickets.SCENIC_SPOT_NAME
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setScenicSpotName(String scenicSpotName) {
        this.scenicSpotName = scenicSpotName == null ? null : scenicSpotName.trim();
    }
}