package com.yunhe.common.model.domain;

public class Users extends UsersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PASSWORD
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_PHONE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    private String userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PASSWORD
     *
     * @return the value of users.PASSWORD
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.PASSWORD
     *
     * @param password the value for users.PASSWORD
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_PHONE
     *
     * @return the value of users.USER_PHONE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER_PHONE
     *
     * @param userPhone the value for users.USER_PHONE
     *
     * @mbg.generated Mon Jan 11 12:58:19 CST 2021
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }
}