server:
  port: 8003

spring:
  application:
    name: yh-orders
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/order_schema?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
